name: Node.js CI

on:
  pull_request:
    branches:
      - main
      - main-v[0-9]+

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
      - run: yarn install
      - run: yarn build:prod
